#!/usr/bin/env sh
. "$(dirname -- "$0")/_/husky.sh"

echo "stashing staged changes to preserve them for the commit"
git commit -m 'husky - Save index' --no-verify --quiet
echo "creating temp file so there is always something to stash"
touch huskytemp
echo "stashing changes not already added for the commit" 
git stash --include-untracked -m "husky - unstaged changes" --quiet
echo "restoring staged changes from the stash" 
git reset --soft HEAD^ --quiet

# in git versions 2.25 and later, the following commands can be used instead of the above commands
# echo "stashing staged changes to preserve them for the commit"
# git stash push --staged -m "husky - staged changes"    
# echo "stashing changes not already added for the commit" 
# git stash --include-untracked -m "husky - unstaged changes"
# echo "restoring staged changes from the stash" 
# git stash pop stash@{1}

echo "backing up docker-compose.yml to docker-compose.yml.huskybackup" 
cp docker-compose.yml docker-compose.yml.huskybackup
echo "uncommenting secure lines in docker-compose.yml..." 
sed -i -E '/#\s*secure/ s/^(\s*)#\s*(.+)/\1\2/' docker-compose.yml
echo "commenting dev lines in docker-compose.yml..." 
sed -i -E '/#\s*dev/ s/^(\s*)(#*)(.*)/\1#\3/' docker-compose.yml
echo "commenting testcoverage lines in docker-compose.yml..." 
sed -i -E '/#\s*testcoverage/ s/^(\s*)(#*)(.*)/\1#\3/' docker-compose.yml

echo "running format..." 
npm run --silent format

echo "adding all files to the commit that were changed by formatting" 
git add . 

echo "restoring the stashed changes" 
git stash pop --quiet
echo "deleting temp file" 
rm huskytemp

echo "restoring backed up docker-compose.yml" 
cp docker-compose.yml.huskybackup docker-compose.yml
